### ISSUE TITLE
ACRA

### ISSUE THREAD

**Issue by IzzySoft** [openvk/mobile-android-legacy#153]
I've noticed your latest release added ACRA. May I ask if it's configured opt-in – or opt-out? Are users informed before (and what) is sent? Seeing [`org.acra.BaseCrashReportDialog`](https://github.com/openvk/mobile-android-legacy/blob/98e7a4a80a5e0c59bd01674b54eff96bcbd89bb6/app/src/main/java/uk/openvk/android/legacy/ui/core/activities/CrashReporterActivity.java#L20) being included suggests you use the "popup and tell the user to decide after they investigated what will be sent" variant. Is that correct?

Neither app description nor Readme or release notes state anything on this (apart from ACRA being mentioned in the Readme). May I suggest to add it there, how it is used? Thanks in advance!

**Comment by tretdm** [comment]
In this case, ACRA does not automatically send data (including the error report) to the developers, because [there is no feedback](https://github.com/openvk/mobile-android-legacy/blob/98e7a4a80a5e0c59bd01674b54eff96bcbd89bb6/app/src/main/java/uk/openvk/android/legacy/OvkApplication.java#L44-L50).

In the [`CrashReportActivity` place](https://github.com/openvk/mobile-android-legacy/blob/main/app/src/main/java/uk/openvk/android/legacy/ui/core/activities/CrashReporterActivity.java) you can see a dialog window, to fix which you need to send this crash report yourself.

![Screenshot_20231121-053401879](https://github.com/openvk/mobile-android-legacy/assets/76806170/fdb5e804-1f70-44a3-ad74-b19d0b0731dd)

**Comment by IzzySoft** [comment]
Perfect, thanks! Achievement unlocked: I've told my updater this does **not** mean `AntiFeatures: Tracking` :smile:
